name: CI/CD for Todometer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout kodu
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instalacja Node.js, zmiana na 20 a było 23
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

# Konfiguracja cache dla zależności npm
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-

      # Instalacja zależności
      - name: Install dependencies
        run: npm install

      # Testy jednostkowe (prawdopodobnie)
      - name: Run unit tests
        run: npm test

      # Budowanie aplikacji
      - name: Build app
        run: npm run build

      - name: Npm audit test #w ramach SCA
        continue-on-error: true
        run: npm install --package-lock-only && npm audit --json > audit-report.json
       # run: npm audit --json > audit-report.json

      - name: Upload audit report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: audit-report.json

#Tego jeszcze nie jestem pewna czy tak zostanie czy inny linter użyje
      - name: Super-linter
        continue-on-error: true
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_1 }}


  security_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Konfiguracja cache dla zależności npm (w przypadku potrzeby w tym kroku)
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
           npm-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check outdated
        continue-on-error: true
        run: npm outdated --json > outdated-report.json

      - name: Upload outdated report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-outdated-report
          path: outdated-report.json
          
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@3.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


#testing snyk
 #     - name: Run Snyk Code Analysis
      #  continue-on-error: true
  #      uses: snyk/actions/node@master
   #     env:
    #      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #  with:
     #     args: test --code --json > snyk-code-report.json

      # Upload wyniku jako artefakt
      #- name: Upload Snyk Code report as artifact
      #  uses: actions/upload-artifact@v4
       # with:
        #  name: snyk-code-report
         # path: snyk-code-report.json


#  other_tests:
#    permissions:
 #     contents: read
 #   needs: build
  #  runs-on: ubuntu-latest
   # steps:
# Konfiguracja cache dla zależności npm
    #  - name: Cache npm dependencies
     #   uses: actions/cache@v4
      #  with:
       #   path: ~/.npm
        #  key: npm-${{ hashFiles('package-lock.json') }}
         # restore-keys: |
          #  npm-

      # Instalacja Node.js, zmiana na 20 a było 23
     # - name: Setup Node.js
      #  uses: actions/setup-node@v4
       # with:
        #  node-version: '20' 

   #   - name: Dependency Review
    #    id: dep_rev
     #   uses: actions/dependency-review-action@v4 

 #     - name: Save Dependency Review Report
  #      run: |
   #       echo "${{ steps.dependency_review.outputs.report }}" > dependency-review-report.json

    #  - name: Upload Dependency Review Report as artifact
     #   uses: actions/upload-artifact@v4
      #  with:
       #   name: dependency-review-report
        #  path: dependency-review-report.json


#Tego jeszcze nie jestem pewna czy tak zostanie czy inny linter użyje
    #  - name: Super-linter
     #   continue-on-error: true
      #  uses: super-linter/super-linter@v7.1.0
       # env:
        #  GITHUB_TOKEN: ${{ secrets.SECRET_1 }}
